### ISSUE TITLE
Call to undefined method Interwiki::fetch()

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExternalQueryLookup#33]
### Setup and configuration
- MediaWiki | 1.35.0-rc.2 (5f6c9d1)16:32, 21 August 2020
- PHP | 7.2.24-0ubuntu0.18.04.7 (apache2handler)
- MariaDB | 10.1.47-MariaDB-0ubuntu0.18.04.1
- Elasticsearch | 6.5.4

### Issue
[98d7e10a2693aa30c5a558aa] /wiki/My_first_external_query Error from line 59 of /../w/extensions/SemanticExternalQueryLookup/src/ByHttpRequestQueryLookup.php: Call to undefined method Interwiki::fetch()

### Backtrace
```
#0 /../w/extensions/SemanticExternalQueryLookup/src/ByHttpRequestQueryLookup.php(48): SEQL\ByHttpRequestQueryLookup->tryToMatchInterwikiFor(SMWQuery)
#1 /../w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(338): SEQL\ByHttpRequestQueryLookup->getQueryResult(SMWQuery)
#2 /../w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(364): SMWQueryProcessor::getResultFromQuery(SMWQuery, array, integer, integer)
#3 /../w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(197): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters(array, array)
#4 /../w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(402): SMW\ParserFunctions\AskParserFunction->parse(array)
#5 /../w/includes/parser/Parser.php(3340): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string, string, string, string, string, string)
#6 /../w/includes/parser/Parser.php(3047): Parser->callParserFunction(PPFrame_Hash, string, array)
#7 /../w/includes/parser/PPFrame_Hash.php(253): Parser->braceSubstitution(array, PPFrame_Hash)
#8 /../w/includes/parser/Parser.php(2887): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)
#9 /../w/includes/parser/Parser.php(1556): Parser->replaceVariables(string)
#10 /../w/includes/parser/Parser.php(651): Parser->internalParse(string)
#11 /../w/includes/content/WikitextContent.php(374): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#12 /../w/includes/content/AbstractContent.php(590): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#13 /../w/includes/Revision/RenderedRevision.php(266): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
#14 /../w/includes/Revision/RenderedRevision.php(235): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(WikitextContent, boolean)
#15 /../w/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string)
#16 /../w/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#17 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#18 /../w/includes/Revision/RenderedRevision.php(197): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#19 /../w/includes/poolcounter/PoolWorkArticleView.php(216): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#20 /../w/includes/poolcounter/PoolCounterWork.php(162): PoolWorkArticleView->doWork()
#21 /../w/includes/page/Article.php(810): PoolCounterWork->execute()
#22 /../w/includes/actions/ViewAction.php(74): Article->view()
#23 /../w/includes/MediaWiki.php(527): ViewAction->show()
#24 /../w/includes/MediaWiki.php(313): MediaWiki->performAction(Article, Title)
#25 /../w/includes/MediaWiki.php(940): MediaWiki->performRequest()
#26 /../w/includes/MediaWiki.php(543): MediaWiki->main()
#27 /../w/index.php(53): MediaWiki->run()
#28 /../w/index.php(46): wfIndexMain()
#29 {main}
```

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

[--> test page](https://sandbox.semantic-mediawiki.org/wiki/My_first_external_query)

**Comment by datawiki** [comment]
Getting the same Interwiki::fetch() undefined method error.  Is there a no pressure (not that that exists :) let's see maybe date?
